# Use Python base image
FROM python

# Set the working directory inside the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Set the command to run the app
CMD ["python", "app.py"]
